MERCHANT_CODE = "test"
TERMINAL_CODE = "test"

PRIVATE_KEY_PEM = b"""test"""


TERMINAL_BASE_URL = 'https://test.ir'
TERMINAL_GET_PEYMENT_TOKEN_URL = 'url1'    
TERMINAL_USER_REDIRECT_TO_PAY = "ur2"
TERMINAL_CHECK_RESULT = "url3"
TERMINAL_PAYMENT_VERTIFY = "url4"