"""
Django settings for nursing_system project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from celery.schedules import crontab
from pathlib import Path
import os


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-a4amc7^348dqw3v3pq7m96ij32rdd7yass$o&scjr(ap=ks6r('

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'django.contrib.gis',
    'django.contrib.sitemaps',

    # third-party packages
    'django_cleanup.apps.CleanupConfig',
    'django_celery_results',
    'django_celery_beat',
    "django_flatpickr",
    'django_jalali',
    'django_redis',
    'storages',
    'tinymce',

    # project apps  
    'home.apps.HomeConfig',
    'normal_users.apps.NormalUsersConfig',
    'nurse_users.apps.NurseUsersConfig',
    'services.apps.ServicesConfig',
    'articles.apps.ArticlesConfig',
    'payment.apps.PaymentConfig',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

]

ROOT_URLCONF = 'nursing_system.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'home.context_processors.base_template_processor',
            ],
        },
    },
]

WSGI_APPLICATION = 'nursing_system.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.contrib.gis.db.backends.postgis",
        "NAME": os.getenv("DB_DEFAULT_NAME", "user_defaultdb1"),
        "USER": os.getenv("DB_USER", "bouta"),
        "PASSWORD": os.getenv("DB_PASSWORD", "bouta"),
        "HOST": os.getenv("DB_HOST", "postgres"),
        "PORT": os.getenv("DB_PORT", "5432"),
    },

    "content_db": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("DB_CONTENT_NAME", "contentdb1"),
        "USER": os.getenv("DB_USER", "bouta"),
        "PASSWORD": os.getenv("DB_PASSWORD", "bouta"),
        "HOST": os.getenv("DB_HOST", "postgres"),
        "PORT": os.getenv("DB_PORT", "5432"),
    },

    "services_db": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("DB_SERVICES_NAME", "servicesdb1"),
        "USER": os.getenv("DB_USER", "bouta"),
        "PASSWORD": os.getenv("DB_PASSWORD", "bouta"),
        "HOST": os.getenv("DB_HOST", "postgres"),
        "PORT": os.getenv("DB_PORT", "5432"),
    },
}

DATABASE_ROUTERS = ['nursing_system.database_router.MultiDBRouter']


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Tehran'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATICFILES_DIRS = [

    os.path.join(BASE_DIR, 'static')
]
STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Local media storage
MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# custom user model 
AUTH_USER_MODEL = 'normal_users.CustomUser'


# tinymce (the admin text field)
TINYMCE_DEFAULT_CONFIG = {
    'height': 360,
    'width': 'auto',
    'plugins': 'image link media code',
    'toolbar': 'undo redo | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image media | code',
    'image_caption': True,
    'image_advtab': True,
    'file_picker_types': 'image',
    'automatic_uploads': True,
    'images_upload_url': '/tinymce/upload/',  # This URL will handle the image upload
    'images_upload_credentials': True,  # Use credentials for uploading images
}

# jalali settings
JALALI_SETTINGS = {
    # JavaScript static files for the admin Jalali date widget
    "ADMIN_JS_STATIC_FILES": [
        "admin/jquery.ui.datepicker.jalali/scripts/jquery-1.10.2.min.js",
        "admin/jquery.ui.datepicker.jalali/scripts/jquery.ui.core.js",
        "admin/jquery.ui.datepicker.jalali/scripts/jquery.ui.datepicker-cc.js",
        "admin/jquery.ui.datepicker.jalali/scripts/calendar.js",
        "admin/jquery.ui.datepicker.jalali/scripts/jquery.ui.datepicker-cc-fa.js",
        "admin/main.js",
    ],
    # CSS static files for the admin Jalali date widget
    "ADMIN_CSS_STATIC_FILES": {
        "all": [
            "admin/jquery.ui.datepicker.jalali/themes/base/jquery-ui.min.css",
            "admin/css/main.css",
        ]
    },
}


# cache backend(redis) used for rate limiting 
CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',  # Using the Redis cache backend
        'LOCATION': 'redis://redis:6379/1',  # Redis server, change as necessary
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',  # Default Redis client
            'CONNECTION_POOL': {
                'MAX_CONNECTIONS': 100,  # Max number of connections to Redis
                'CONN_TIMEOUT': 5,  # Connection timeout in seconds
            },
            'SOCKET_TIMEOUT': 5,  # Timeout for reading from Redis
            'SOCKET_CONNECT_TIMEOUT': 5,  # Timeout for establishing Redis connection
            'PICKLE_VERSION': 2,  # Pickle version for serializing objects
        },
        'KEY_PREFIX': 'ratelimit:',  # Prefix for cache keys to avoid collisions
        'TIMEOUT': 60,  # Default TTL for cache keys, 60 seconds for rate limiting
        'VERSION': 1,  # Cache versioning
    }
}

CELERY_BROKER_URL = 'redis://redis:6379/0'
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_BACKEND = 'django-db'
CELERY_TIMEZONE = 'Asia/Tehran'


CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'


# temp_dir not in production any more
TEMP_UPLOAD_DIR = os.path.join(BASE_DIR, 'temp_uploads')

if not os.path.exists(TEMP_UPLOAD_DIR):
    os.makedirs(TEMP_UPLOAD_DIR)


TIME_INPUT_FORMATS = ('%H:%M',)






# fixing open street map tiles
SECURE_REFERRER_POLICY = "strict-origin-when-cross-origin"