# Generated by Django 5.0 on 2025-02-04 09:49

import django_jalali.db.models
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان دسته\u200cبندی')),
                ('description', models.CharField(max_length=200, verbose_name='توضیح دسته بندی')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='آدرس دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی',
                'verbose_name_plural': 'دسته\u200cبندی ها',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='عنوان مقاله را وارد کنید', max_length=200, verbose_name='عنوان مقاله')),
                ('slug', models.SlugField(help_text='آدرس مقاله را میتوانید از اینجا عوض کنید،(نکته: فقط در زمان ویرایش مقاله امکان تغییر آدرس وجود دارد) اما با عوض کردن آن آدرس قبلی در دسترس نخواهد بود', max_length=100, unique=True, verbose_name='آدرس مقاله')),
                ('description', tinymce.models.HTMLField(help_text='محتوای مقاله را وارد کنید', verbose_name='مقاله')),
                ('description_short', models.TextField(blank=True, null=True, verbose_name='توضیح کوتاه')),
                ('thumbnail', models.ImageField(help_text='تصویری که میخواهید به عنوان کاور مقاله قرار بگیرد را وارد کنید', upload_to='storage/articles/', verbose_name='تصویر مقاله')),
                ('meta_thumbnail', models.CharField(max_length=124, verbose_name='متا عکس')),
                ('jalali_datetime', django_jalali.db.models.jDateTimeField(verbose_name='زمان انتشار جلالی ')),
                ('status', models.BooleanField(default=True, verbose_name='وضعیت انتشار')),
                ('category', models.ManyToManyField(help_text='دسته بندی پست خود را وارد کنید', related_name='blog', to='articles.category', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات',
                'ordering': ['-id'],
            },
        ),
    ]
