# Generated by Django 5.0 on 2025-03-12 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_category_star'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='star',
            field=models.BooleanField(default=False),
        ),
    ]
