# Generated by Django 5.0 on 2025-03-14 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_alter_category_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseTemplateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='storage/home/')),
                ('email', models.CharField(max_length=124)),
                ('address', models.TextField(max_length=500)),
                ('phone_number', models.TextField(max_length=124)),
                ('footer_description', models.TextField(max_length=300)),
            ],
            options={
                'verbose_name': 'اطلاعات پایه ای سایت',
                'verbose_name_plural': 'اطلاعات پایه ای سایت',
            },
        ),
    ]
