# Generated by Django 5.0 on 2025-03-14 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_basetemplatemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='basetemplatemodel',
            name='logo2',
            field=models.ImageField(null=True, upload_to='storage/home/'),
        ),
        migrations.AddField(
            model_name='basetemplatemodel',
            name='logo3',
            field=models.ImageField(null=True, upload_to='storage/home/'),
        ),
    ]
