# Generated by Django 5.0 on 2025-03-14 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_basetemplatemodel_logo2_basetemplatemodel_logo3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basetemplatemodel',
            name='logo2',
            field=models.ImageField(default='1', upload_to='storage/home/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='basetemplatemodel',
            name='logo3',
            field=models.ImageField(default='1', upload_to='storage/home/'),
            preserve_default=False,
        ),
    ]
