# Generated by Django 5.0 on 2025-03-14 13:09

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_alter_basetemplatemodel_logo2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexTemplateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='storage/home/')),
                ('image2', models.ImageField(upload_to='storage/home/')),
                ('about1_title', models.CharField(max_length=500)),
                ('about1_description', tinymce.models.HTMLField()),
                ('about2_title', models.CharField(max_length=500)),
                ('about2_description', tinymce.models.HTMLField()),
            ],
            options={
                'verbose_name': 'اطلاعات صفحه اصلی',
                'verbose_name_plural': 'اطلاعات صفحه اصلی',
            },
        ),
    ]
