# Generated by Django 5.0 on 2025-03-14 18:35

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_indextemplatemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceTemplateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_title', models.CharField(max_length=124)),
                ('first_description', tinymce.models.HTMLField()),
            ],
            options={
                'verbose_name': 'اطلاعات صفحه خدمات',
                'verbose_name_plural': 'اطلاعات صفحه خدمات',
            },
        ),
    ]
