# Generated by Django 5.0 on 2025-03-15 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_servicetemplatemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrequentQuestionsTemplateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('answer', models.TextField()),
            ],
            options={
                'verbose_name': 'اطلاعات صفحه پرسش های متداول',
                'verbose_name_plural': 'اطلاعات صفحه پرسش های متداول',
            },
        ),
    ]
