# Generated by Django 5.0 on 2025-03-15 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_frequentquestionstemplatemodel_display_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUsTemplateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email1', models.CharField(max_length=124)),
                ('email2', models.CharField(max_length=124)),
                ('phone_number1', models.CharField(max_length=20)),
                ('phone_number2', models.CharField(max_length=20)),
                ('address', models.TextField()),
            ],
            options={
                'verbose_name': 'اطلاعات صفحه ارتباط با ما',
                'verbose_name_plural': 'اطلاعات صفحه ارتباط با ما',
            },
        ),
    ]
