# Generated by Django 5.0 on 2025-03-15 09:32

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_contactustemplatemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermsTemplateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', tinymce.models.HTMLField()),
            ],
            options={
                'verbose_name': 'اطلاعات صفحه شرایط و قوانین',
                'verbose_name_plural': 'اطلاعات صفحه شرایط و قوانین',
            },
        ),
    ]
