# Generated by Django 5.0 on 2025-03-15 11:27

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0014_termstemplatemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryTemplateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', tinymce.models.HTMLField()),
            ],
            options={
                'verbose_name': 'اطلاعات صفحه سوابق ما',
                'verbose_name_plural': 'اطلاعات صفحه سوابق ما ',
            },
        ),
    ]
