# Generated by Django 5.0 on 2025-03-15 11:50

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0015_historytemplatemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='historytemplatemodel',
            name='description2',
            field=tinymce.models.HTMLField(default=''),
        ),
        migrations.AddField(
            model_name='historytemplatemodel',
            name='description3',
            field=tinymce.models.HTMLField(default=''),
        ),
    ]
