# Generated by Django 5.0 on 2025-03-15 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0016_historytemplatemodel_description2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historytemplatemodel',
            name='title1',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='historytemplatemodel',
            name='title2',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='historytemplatemodel',
            name='title3',
            field=models.CharField(default='', max_length=200),
        ),
    ]
