# Generated by Django 5.0 on 2025-06-02 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0017_historytemplatemodel_title1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='indextemplatemodel',
            name='image1_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='indextemplatemodel',
            name='image2_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
