# Generated by Django 5.0 on 2025-06-02 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0018_indextemplatemodel_image1_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='indextemplatemodel',
            name='first_image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
