# Generated by Django 5.0 on 2025-06-03 12:07

import articles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0019_indextemplatemodel_first_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='thumbnail',
            field=models.ImageField(help_text='تصویری که میخواهید به عنوان کاور مقاله قرار بگیرد را وارد کنید', upload_to=articles.models.article_picture_path, verbose_name='تصویر مقاله'),
        ),
    ]
