# Generated by Django 5.0 on 2025-02-17 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normal_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_name',
            field=models.CharField(max_length=124, unique=True),
        ),
    ]
