# Generated by Django 5.0 on 2025-02-25 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normal_users', '0003_alter_customuser_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='province',
            field=models.CharField(choices=[('Tehran', 'تهران'), ('Isfahan', 'اصفهان'), ('Fars', 'فارس'), ('Khorasan Razavi', 'خراسان رضوی'), ('Mazandaran', 'مازندران'), ('Kerman', 'کرمان'), ('East Azerbaijan', 'آذربایجان شرقی'), ('West Azerbaijan', 'آذربایجان غربی'), ('Kurdistan', 'کردستان'), ('Golestan', 'گلستان'), ('Alborz', 'البرز'), ('Semnan', 'سمنان'), ('Lorestan', 'لرستان'), ('Yazd', 'یزد'), ('Khuzestan', 'خوزستان'), ('Markazi', 'مرکزی'), ('Qazvin', 'قزوین'), ('Kohgiluyeh and Boyer-Ahmad', 'کهگیلویه و بویراحمد'), ('Hamedan', 'همدان'), ('Qom', 'قم'), ('Chaharmahal and Bakhtiari', 'چهارمحال و بختیاری'), ('Gilan', 'گیلان'), ('Ardabil', 'اردبیل'), ('Zanjan', 'زنجان'), ('Bushehr', 'بوشهر'), ('Sistan and Baluchestan', 'سیستان و بلوچستان'), ('Hormozgan', 'هرمزگان'), ('Ilam', 'ایلام'), ('South Khorasan', 'خراسان جنوبی'), ('North Khorasan', 'خراسان شمالی')], default='Tehran', max_length=50),
        ),
    ]
