# Generated by Django 5.0 on 2025-03-08 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normal_users', '0006_alter_customuser_province'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='average_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='rating_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
