# Generated by Django 5.0 on 2025-02-04 09:49

import django.core.validators
import django.db.models.deletion
import django_jalali.db.models
import jdatetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_request_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('user', models.UUIDField()),
                ('nurse', models.UUIDField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('payment_pending', 'Payment Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('service_detail_user', models.TextField()),
                ('created_at', django_jalali.db.models.jDateTimeField(default=jdatetime.datetime.now)),
            ],
            options={
                'verbose_name': 'درخواست خدمات',
                'verbose_name_plural': 'درخواست خدمات',
            },
        ),
        migrations.CreateModel(
            name='ServicesList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('price_desription', models.CharField(max_length=150)),
                ('date_updated', django_jalali.db.models.jDateField(verbose_name='آخرین آپدیت')),
                ('standard_price', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'لیست خدمات',
                'verbose_name_plural': 'لیست خدمات',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('user_rating', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('user_review', models.TextField(blank=True, null=True)),
                ('nurse_rating', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('nurse_review', models.TextField(blank=True, null=True)),
                ('created_at', django_jalali.db.models.jDateTimeField(default=jdatetime.datetime.now)),
                ('service_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='services.servicerequest')),
            ],
            options={
                'verbose_name': 'امتیاز دهی',
                'verbose_name_plural': 'امتیاز دهی',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('amount', models.PositiveIntegerField()),
                ('payment_status', models.BooleanField(default=False)),
                ('payment_date', django_jalali.db.models.jDateTimeField()),
                ('service_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='services.servicerequest')),
            ],
            options={
                'verbose_name': 'پرداخت',
                'verbose_name_plural': 'پرداخت ها',
            },
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_request', to='services.serviceslist'),
        ),
    ]
