# Generated by Django 5.0 on 2025-02-21 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequest',
            name='service',
        ),
        migrations.DeleteModel(
            name='ServicesList',
        ),
    ]
