# Generated by Django 5.0 on 2025-02-21 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_remove_servicerequest_service_delete_serviceslist'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='skill_uuid',
            field=models.UUIDField(default='931433dd-8302-41be-b3d0-c6d92de78e49'),
        ),
    ]
