# Generated by Django 5.0 on 2025-02-21 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_servicerequest_skill_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='skill_uuid',
            field=models.UUIDField(),
        ),
    ]
