# Generated by Django 5.0 on 2025-02-21 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_servicerequest_skill_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
