# Generated by Django 5.0 on 2025-02-23 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_alter_servicerequest_service_request_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequest',
            name='skill_uuid',
        ),
    ]
