# Generated by Django 5.0 on 2025-02-23 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_remove_servicerequest_skill_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='skill_slug',
            field=models.SlugField(allow_unicode=True, default='test/'),
            preserve_default=False,
        ),
    ]
