# Generated by Django 5.0 on 2025-02-23 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_servicerequest_skill_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicerequest',
            old_name='created_at',
            new_name='j_created_at',
        ),
    ]
