# Generated by Django 5.0 on 2025-02-23 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_rename_created_at_servicerequest_j_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='1999-02-02 22:02'),
            preserve_default=False,
        ),
    ]
