# Generated by Django 5.0 on 2025-02-23 09:49

import django_jalali.db.models
import jdatetime
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_servicerequest_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='j_update_at',
            field=django_jalali.db.models.jDateTimeField(default=jdatetime.datetime.now),
        ),
    ]
