# Generated by Django 5.0 on 2025-02-23 09:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_alter_payment_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rating_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
