# Generated by Django 5.0 on 2025-02-23 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_alter_rating_rating_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subskill', models.UUIDField()),
                ('price', models.PositiveBigIntegerField()),
                ('quantity', models.PositiveIntegerField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_item', to='services.servicerequest')),
            ],
            options={
                'verbose_name': 'خدمات داخل درخواست',
                'verbose_name_plural': 'خدمات داخل درخواست',
                'ordering': ('-id',),
            },
        ),
    ]
