# Generated by Django 5.0 on 2025-02-23 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_serviceitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='closed',
            field=models.BooleanField(default=False),
        ),
    ]
