# Generated by Django 5.0 on 2025-02-23 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0016_servicerequest_closed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='service_detail_user',
            field=models.TextField(max_length=1000),
        ),
    ]
