# Generated by Django 5.0 on 2025-02-23 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0017_alter_servicerequest_service_detail_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='payment_date',
            new_name='j_payment_date',
        ),
    ]
