# Generated by Django 5.0 on 2025-02-23 13:57

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0018_rename_payment_date_payment_j_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='j_payment_date',
            field=django_jalali.db.models.jDateTimeField(blank=True, null=True),
        ),
    ]
