# Generated by Django 5.0 on 2025-02-24 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0019_payment_payment_date_alter_payment_j_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='nurse',
            field=models.UUIDField(db_index=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='user',
            field=models.UUIDField(db_index=True),
        ),
    ]
