# Generated by Django 5.0 on 2025-02-24 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0020_alter_servicerequest_nurse_alter_servicerequest_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار تایید'), ('accepted', 'پذیرفته شده و در حال اجرا'), ('payment_pending', 'در انتظار پرداخت'), ('completed', 'پایان یافته'), ('cancelled', 'لفو شده')], db_index=True, default='pending', max_length=20),
        ),
    ]
