# Generated by Django 5.0 on 2025-02-25 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0021_alter_servicerequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceitem',
            name='subskill_title',
            field=models.CharField(default='test', max_length=124),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='skill_title',
            field=models.CharField(default='test', max_length=124),
            preserve_default=False,
        ),
    ]
