# Generated by Django 5.0 on 2025-02-26 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0022_serviceitem_subskill_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='service_detail_user',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
