# Generated by Django 5.0 on 2025-02-27 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0023_alter_servicerequest_service_detail_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=124)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'کمیسیون سامانه',
                'verbose_name_plural': 'کمیسیون سامانه',
            },
        ),
    ]
