# Generated by Django 5.0 on 2025-02-27 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0025_payment_commission_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='net_amount',
            field=models.PositiveIntegerField(default=22),
            preserve_default=False,
        ),
    ]
