# Generated by Django 5.0 on 2025-02-27 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0026_payment_net_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicerequest',
            options={'ordering': ('-j_created_at',), 'verbose_name': 'درخواست خدمات', 'verbose_name_plural': 'درخواست خدمات'},
        ),
    ]
