# Generated by Django 5.0 on 2025-02-28 09:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0027_alter_servicerequest_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='NurseWallet',
            fields=[
                ('nurse_id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('balance', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'کیف پول پرستار',
                'verbose_name_plural': 'کیف پول پرستار',
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('transaction_type', models.CharField(choices=[('واریز', 'واریز'), ('برداشت', 'برداشت')], max_length=8)),
                ('amount', models.PositiveBigIntegerField()),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='services.nursewallet')),
            ],
            options={
                'verbose_name': 'تراکنش های کیف پول',
                'verbose_name_plural': 'تراکنش های کیف پول',
                'ordering': ['-timestamp'],
            },
        ),
    ]
