# Generated by Django 5.0 on 2025-02-28 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0028_nursewallet_wallettransaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'پرداخت خدمت', 'verbose_name_plural': 'پرداخت خدمت'},
        ),
        migrations.AlterModelOptions(
            name='rating',
            options={'verbose_name': 'امتیاز دهی خدمت', 'verbose_name_plural': 'امتیاز دهی خدمت'},
        ),
    ]
