# Generated by Django 5.0 on 2025-02-28 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0029_alter_payment_options_alter_rating_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nursewallet',
            name='nurse_id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
