# Generated by Django 5.0 on 2025-03-02 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0030_alter_nursewallet_nurse_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار تایید'), ('accepted', 'پذیرفته شده و در حال اجرا'), ('payment_pending', 'در انتظار پرداخت'), ('completed', 'پایان یافته'), ('cancelled', 'لفو شده'), ('reject', 'رد شده')], db_index=True, default='pending', max_length=20),
        ),
    ]
