# Generated by Django 5.0 on 2025-03-02 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0031_alter_servicerequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار تایید'), ('accepted', 'پذیرفته شده و در حال اجرا'), ('payment_pending', 'در انتظار پرداخت'), ('completed', 'پایان یافته'), ('cancelled', 'لفو شده'), ('reject', 'رد شده'), ('user_cancelled', 'لغو توسط کاربر')], db_index=True, default='pending', max_length=20),
        ),
    ]
