# Generated by Django 5.0 on 2025-03-03 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0034_alter_servicerequest_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='nursewallet',
            name='bank_info',
            field=models.CharField(default='1', max_length=124),
            preserve_default=False,
        ),
    ]
