# Generated by Django 5.0 on 2025-03-03 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0035_nursewallet_bank_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nursewallet',
            name='bank_info',
            field=models.CharField(blank=True, max_length=124, null=True),
        ),
    ]
