# Generated by Django 5.0 on 2025-03-07 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0037_alter_servicerequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
