# Generated by Django 5.0 on 2025-03-08 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0038_rating_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='nurse_review',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='user_review',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
