# Generated by Django 5.0 on 2025-03-09 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0039_alter_rating_nurse_review_alter_rating_user_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.UUIDField(editable=False, unique=True)),
                ('description', models.TextField(max_length=1000)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ریپورت های کاربران',
                'verbose_name_plural': 'ریپورت های کاربران',
                'ordering': ('-updated_at',),
            },
        ),
    ]
