# Generated by Django 5.0 on 2025-03-09 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0041_nursereport'),
    ]

    operations = [
        migrations.AddField(
            model_name='nursereport',
            name='checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userreport',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
