# Generated by Django 5.0 on 2025-03-09 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0042_nursereport_checked_userreport_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='nursereport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2000-01-01 22:33'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userreport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2000-01-01 22:33'),
            preserve_default=False,
        ),
    ]
