# Generated by Django 5.0 on 2025-03-10 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0043_nursereport_created_at_userreport_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nursewallet',
            name='bank_info',
        ),
    ]
