# Generated by Django 5.0 on 2025-03-10 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0044_remove_nursewallet_bank_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='nursewallet',
            name='bank_info',
            field=models.CharField(blank=True, max_length=124, null=True),
        ),
        migrations.AddField(
            model_name='nursewallet',
            name='valid_bank_info',
            field=models.BooleanField(default=False),
        ),
    ]
