# Generated by Django 5.0 on 2025-03-10 09:47

import django.db.models.deletion
import django_jalali.db.models
import jdatetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0045_nursewallet_bank_info_nursewallet_valid_bank_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankInfoRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_info', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('pending', 'در حال بررسی'), ('approved', 'تایید شده'), ('rejected', 'رد شده')], default='pending', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('j_update_at', django_jalali.db.models.jDateTimeField(default=jdatetime.datetime.now)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_info_requests', to='services.nursewallet')),
            ],
            options={
                'verbose_name': 'درخواست بررسی اطلاعات بانکی',
                'verbose_name_plural': 'درخواست بررسی اطلاعات بانکی',
                'ordering': ['-created_at'],
            },
        ),
    ]
