# Generated by Django 5.0 on 2025-03-10 17:11

import django_jalali.db.models
import jdatetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0046_bankinforequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='NursePayRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nurse', models.UUIDField()),
                ('amount', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'در حال بررسی'), ('completed', 'انجام شده'), ('failed', 'ناموفق')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('j_update_at', django_jalali.db.models.jDateTimeField(default=jdatetime.datetime.now)),
            ],
            options={
                'verbose_name': 'درخواست های واریز',
                'verbose_name_plural': 'درخواست های واریز',
                'ordering': ('-updated_at',),
            },
        ),
    ]
