# Generated by Django 5.0 on 2025-03-10 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0047_nursepayrequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nursepayrequest',
            options={'ordering': ('-created_at',), 'verbose_name': 'درخواست های واریز', 'verbose_name_plural': 'درخواست های واریز'},
        ),
    ]
