# Generated by Django 5.0 on 2025-03-10 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0048_alter_nursepayrequest_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nursepayrequest',
            name='nurse',
            field=models.UUIDField(db_index=True),
        ),
    ]
