# Generated by Django 5.0 on 2025-03-10 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0049_alter_nursepayrequest_nurse'),
    ]

    operations = [
        migrations.AddField(
            model_name='nursepayrequest',
            name='wallet',
            field=models.ForeignKey(default='e0fea61c-c6a7-4be6-b221-fdf6192d4819', on_delete=django.db.models.deletion.CASCADE, related_name='pay_request', to='services.nursewallet'),
            preserve_default=False,
        ),
    ]
