# Generated by Django 5.0 on 2025-03-11 08:19

import django_jalali.db.models
import jdatetime
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0050_nursepayrequest_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='j_time',
            field=django_jalali.db.models.jDateTimeField(default=jdatetime.datetime.now),
        ),
    ]
