# Generated by Django 5.0 on 2025-05-29 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0052_fix_datetime_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField()),
                ('invoice_date', models.DateField(auto_now_add=True)),
                ('invoice_datetime', models.DateTimeField(auto_now_add=True)),
                ('invoice_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_paid', models.BooleanField(db_index=True, default=False)),
                ('transaction_reference_id', models.CharField(blank=True, max_length=124, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_payment', to='services.payment')),
            ],
            options={
                'verbose_name': 'خرید اشتراک',
                'verbose_name_plural': 'خرید اشتراک ها',
                'ordering': ['-created_at'],
            },
        ),
    ]
