# Generated by Django 5.0 on 2025-05-29 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0053_servicepayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepayment',
            name='the_payment_id',
            field=models.UUIDField(default='8ec57726-4978-4c75-ac09-a20a418989aa'),
        ),
    ]
