# Generated by Django 5.0 on 2025-05-29 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0054_servicepayment_the_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepayment',
            name='the_payment_id',
            field=models.UUIDField(),
        ),
    ]
