# Generated by Django 5.0 on 2025-05-29 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0055_alter_servicepayment_the_payment_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicepayment',
            options={'ordering': ['-created_at'], 'verbose_name': 'تراکنش های سرویس', 'verbose_name_plural': 'تراکنش های سرویس'},
        ),
    ]
