# Generated by Django 5.0 on 2025-07-06 04:52

import django_jalali.db.models
import jdatetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0056_alter_servicepayment_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebSiteWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.PositiveBigIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'کیف پول سامانه',
                'verbose_name_plural': 'کیف پول سامانه',
            },
        ),
        migrations.CreateModel(
            name='WebSiteWalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('transaction_type', models.CharField(choices=[('واریز', 'واریز'), ('برداشت', 'برداشت')], max_length=8)),
                ('transaction_source', models.CharField(choices=[('سرویس', 'سرویس'), ('برداشت', 'حق اشتراک')], max_length=20)),
                ('teminal_transaction_id', models.CharField(blank=True, max_length=30, unique=True)),
                ('amount', models.PositiveBigIntegerField()),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('j_time', django_jalali.db.models.jDateTimeField(default=jdatetime.datetime.now)),
            ],
            options={
                'verbose_name': 'تراکنش های کیف پول سامانه',
                'verbose_name_plural': 'تراکنش های کیف پول سامانه',
                'ordering': ['-timestamp'],
            },
        ),
    ]
