# Generated by Django 5.0 on 2025-07-08 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0057_websitewallet_websitewallettransaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='websitewallettransaction',
            old_name='teminal_transaction_id',
            new_name='terminal_transaction_id',
        ),
    ]
