# Generated by Django 5.0 on 2025-07-09 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0058_rename_teminal_transaction_id_websitewallettransaction_terminal_transaction_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WebSiteWallet',
        ),
        migrations.DeleteModel(
            name='WebSiteWalletTransaction',
        ),
    ]
