# Generated by Django 5.0 on 2025-02-04 09:49

import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalKnowledg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=124)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'دانش اضافی',
                'verbose_name_plural': 'دانش های اضافی',
            },
        ),
        migrations.CreateModel(
            name='EducationLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=124)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'مدرک تحصیلی',
                'verbose_name_plural': 'مدرک تحصیلی',
            },
        ),
        migrations.CreateModel(
            name='ModernNursing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=124)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'آشنایی با ابزار های پرستاری مدرن',
                'verbose_name_plural': 'آشنایی با ابزار های پرستاری مدرن',
            },
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=124)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'مهارت',
                'verbose_name_plural': 'مهارت ها',
            },
        ),
        migrations.CreateModel(
            name='NurseUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_user_id', models.UUIDField(db_index=True, editable=False, unique=True)),
                ('first_name', models.CharField(max_length=99)),
                ('last_name', models.CharField(max_length=99)),
                ('birthday', django_jalali.db.models.jDateField(verbose_name='تاریخ تولد')),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('province', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('profile_picture', models.ImageField(upload_to='storage/nurse/profile/')),
                ('phone_number', models.CharField(max_length=11, unique=True)),
                ('ministry_proof_picture', models.ImageField(upload_to='storage/nurse/ministry_proof/')),
                ('address', models.TextField(max_length=300)),
                ('is_active', models.BooleanField(default=False)),
                ('education_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nurse_users.educationlevel')),
            ],
            options={
                'verbose_name': 'پرستار',
                'verbose_name_plural': 'پرستاران',
            },
        ),
        migrations.CreateModel(
            name='RegistrationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_progress', 'در حال بررسی'), ('accepted', 'تأیید شده'), ('pending', 'در انتظار تصحیح توسط کاربر')], default='in_progress', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved', models.BooleanField(default=False)),
                ('nurse', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='register_request', to='nurse_users.nurseuser')),
            ],
            options={
                'verbose_name': 'درخواست عضویت پرستار',
                'verbose_name_plural': 'درخواست های عضویت پرستار',
            },
        ),
        migrations.CreateModel(
            name='NurseUserAdditionalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_knowledg', models.ManyToManyField(default=0, related_name='nurse_user_additional_info', to='nurse_users.additionalknowledg')),
                ('modern_nursing', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='nurse_user_additional_info', to='nurse_users.modernnursing')),
                ('nurse', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nurse_user_additional_info', to='nurse_users.nurseuser')),
                ('skilss', models.ManyToManyField(default=0, related_name='nurse_user_additional_info', to='nurse_users.skills')),
            ],
            options={
                'verbose_name': 'اطلاعات اضافی پرستاران',
                'verbose_name_plural': 'اطلاعات اضافی پرستاران',
            },
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=124)),
                ('description', models.TextField(default='', max_length=500)),
                ('start_work', django_jalali.db.models.jDateField(verbose_name='تاریخ شروع به کار')),
                ('end_work', django_jalali.db.models.jDateField(verbose_name='تاریخ پایان کار')),
                ('nurse_additional_info', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='work_experience', to='nurse_users.nurseuseradditionalinfo')),
            ],
            options={
                'verbose_name': 'مراکزی که پرستار در آن کار کرده',
                'verbose_name_plural': 'مراکزی که پرستار در آن کار کرده',
            },
        ),
        migrations.CreateModel(
            name='WorkingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('zero', 'شنبه'), ('one', 'یکشنبه'), ('two', 'دوشنبه'), ('three', 'سه\u200cشنبه'), ('four', 'چهارشنبه'), ('five', 'پنج\u200cشنبه'), ('six', 'جمعه'), ('all', 'شنبه تا چهارشنبه')], max_length=6)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('part_time', models.BooleanField(default=False)),
                ('nurse_additional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_hours', to='nurse_users.nurseuseradditionalinfo')),
            ],
            options={
                'verbose_name': 'ساعت کاری',
                'verbose_name_plural': 'ساعات کاری',
            },
        ),
    ]
