# Generated by Django 5.0 on 2025-02-04 14:22

import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurse_users', '0002_subscriptionplan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptionplan',
            options={'ordering': ['price'], 'verbose_name': 'طرح اشتراک', 'verbose_name_plural': 'طرح های اشتراک'},
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('start_date_j', django_jalali.db.models.jDateField()),
                ('end_date', models.DateField()),
                ('end_date_j', django_jalali.db.models.jDateField()),
                ('status', models.BooleanField(default=False)),
                ('nurse_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='nurse_users.nurseuser')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_plan', to='nurse_users.subscriptionplan')),
            ],
            options={
                'verbose_name': 'اشتراک',
                'verbose_name_plural': 'اشتراک ها',
            },
        ),
    ]
