# Generated by Django 5.0 on 2025-02-04 15:11

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurse_users', '0004_alter_subscription_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='end_date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='end_date_j',
            field=django_jalali.db.models.jDateTimeField(blank=True),
        ),
    ]
