# Generated by Django 5.0 on 2025-02-05 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurse_users', '0006_alter_subscription_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
