# Generated by Django 5.0 on 2025-02-06 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurse_users', '0008_alter_subscription_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nurseuseradditionalinfo',
            name='additional_knowledg',
            field=models.ManyToManyField(related_name='nurse_user_additional_info', to='nurse_users.additionalknowledg'),
        ),
        migrations.AlterField(
            model_name='nurseuseradditionalinfo',
            name='modern_nursing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nurse_user_additional_info', to='nurse_users.modernnursing'),
        ),
        migrations.AlterField(
            model_name='nurseuseradditionalinfo',
            name='skilss',
            field=models.ManyToManyField(related_name='nurse_user_additional_info', to='nurse_users.skills'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='nurse_additional_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experience', to='nurse_users.nurseuseradditionalinfo'),
        ),
        migrations.AlterField(
            model_name='workinghours',
            name='part_time',
            field=models.BooleanField(),
        ),
    ]
