# Generated by Django 5.0 on 2025-02-06 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurse_users', '0009_alter_nurseuseradditionalinfo_additional_knowledg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nurseuseradditionalinfo',
            name='modern_nursing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nurse_user_additional_info', to='nurse_users.modernnursing'),
        ),
    ]
