# Generated by Django 5.0 on 2025-02-06 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurse_users', '0010_alter_nurseuseradditionalinfo_modern_nursing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nurseuseradditionalinfo',
            name='additional_knowledg',
            field=models.ManyToManyField(blank=True, related_name='nurse_user_additional_info', to='nurse_users.additionalknowledg'),
        ),
        migrations.AlterField(
            model_name='nurseuseradditionalinfo',
            name='skilss',
            field=models.ManyToManyField(blank=True, related_name='nurse_user_additional_info', to='nurse_users.skills'),
        ),
    ]
