# Generated by Django 5.0 on 2025-02-06 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nurse_users', '0011_alter_nurseuseradditionalinfo_additional_knowledg_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nurseuseradditionalinfo',
            old_name='skilss',
            new_name='skills',
        ),
    ]
