# Generated by Django 5.0 on 2025-02-07 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurse_users', '0012_rename_skilss_nurseuseradditionalinfo_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workinghours',
            name='part_time',
        ),
        migrations.AddField(
            model_name='nurseuseradditionalinfo',
            name='part_time',
            field=models.BooleanField(default=False),
        ),
    ]
