# Generated by Django 5.0 on 2025-02-08 14:46

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurse_users', '0013_remove_workinghours_part_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NurseLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=124)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('address', models.TextField(max_length=250)),
                ('province', models.CharField(max_length=124)),
            ],
        ),
        migrations.AddField(
            model_name='nurseuseradditionalinfo',
            name='nurse_location',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nurse_location', to='nurse_users.nurselocation'),
        ),
    ]
