# Generated by Django 5.0 on 2025-02-08 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nurse_users', '0014_nurselocation_nurseuseradditionalinfo_nurse_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nurselocation',
            options={'verbose_name': 'آدرس پرستار', 'verbose_name_plural': 'آدرس پرستاران'},
        ),
    ]
