# Generated by Django 5.0 on 2025-02-09 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurse_users', '0015_alter_nurselocation_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nurselocation',
            name='address',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='nurselocation',
            name='province',
            field=models.CharField(blank=True, max_length=124, null=True),
        ),
        migrations.AlterField(
            model_name='nurselocation',
            name='title',
            field=models.CharField(blank=True, max_length=124, null=True),
        ),
    ]
