# Generated by Django 5.0 on 2025-02-09 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurse_users', '0017_alter_nurseuseradditionalinfo_nurse_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nurseuseradditionalinfo',
            name='nurse_location',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nurse_location', to='nurse_users.nurselocation'),
        ),
    ]
