# Generated by Django 5.0 on 2025-02-11 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurse_users', '0018_alter_nurseuseradditionalinfo_nurse_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='price',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
