# Generated by Django 5.0 on 2025-02-11 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurse_users', '0019_skills_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nurseuseradditionalinfo',
            name='modern_nursing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nurse_user_additional_info', to='nurse_users.modernnursing'),
        ),
    ]
