# Generated by Django 5.0 on 2025-02-11 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurse_users', '0020_alter_nurseuseradditionalinfo_modern_nursing'),
    ]

    operations = [
        migrations.CreateModel(
            name='NurseSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_price', models.PositiveIntegerField()),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nurse_users.nurseuseradditionalinfo')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nurse_users.skills')),
            ],
            options={
                'verbose_name': 'مهارت های انتخاب شده پرستار',
                'verbose_name_plural': 'مهارت های انتخاب شده پرستار',
                'unique_together': {('nurse', 'skill')},
            },
        ),
    ]
