# Generated by Django 5.0 on 2025-02-11 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nurse_users', '0022_alter_nurseskills_custom_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nurseuseradditionalinfo',
            name='skills',
        ),
    ]
