# Generated by Django 5.0 on 2025-02-11 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurse_users', '0023_remove_nurseuseradditionalinfo_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nurseskills',
            name='custom_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
