# Generated by Django 5.0 on 2025-02-11 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurse_users', '0024_alter_nurseskills_custom_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nurseskills',
            name='nurse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nurse_skills', to='nurse_users.nurseuseradditionalinfo'),
        ),
    ]
