# Generated by Django 5.0 on 2025-02-11 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurse_users', '0025_alter_nurseskills_nurse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nurseskills',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill', to='nurse_users.skills'),
        ),
    ]
