# Generated by Django 5.0 on 2025-02-11 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nurse_users', '0026_alter_nurseskills_skill'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nurseskills',
            options={'ordering': ['-id'], 'verbose_name': 'مهارت های انتخاب شده پرستار', 'verbose_name_plural': 'مهارت های انتخاب شده پرستار'},
        ),
    ]
