# Generated by Django 5.0 on 2025-02-11 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nurse_users', '0027_alter_nurseskills_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nurseskills',
            options={'verbose_name': 'مهارت های انتخاب شده پرستار', 'verbose_name_plural': 'مهارت های انتخاب شده پرستار'},
        ),
    ]
