# Generated by Django 5.0 on 2025-02-12 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nurse_users', '0028_alter_nurseskills_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skills',
            old_name='description',
            new_name='price_description',
        ),
    ]
