# Generated by Django 5.0 on 2025-02-12 08:31

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nurse_users', '0029_rename_description_skills_price_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='skill_description',
            field=tinymce.models.HTMLField(default='test'),
            preserve_default=False,
        ),
    ]
