# Generated by Django 5.0 on 2025-02-12 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurse_users', '0031_alter_nurseuser_province'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nurseuser',
            name='province',
            field=models.CharField(max_length=50),
        ),
    ]
