# Generated by Django 5.0 on 2025-02-13 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurse_users', '0033_alter_nurseuser_province'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nurseuseradditionalinfo',
            name='nurse_location',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nurse_location', to='nurse_users.nurselocation'),
        ),
    ]
