# Generated by Django 5.0 on 2025-02-14 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurse_users', '0035_alter_nurseuseradditionalinfo_nurse_location'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='nurselocation',
            index=models.Index(fields=['location'], name='nurse_users_locatio_9250ed_idx'),
        ),
    ]
