# Generated by Django 5.0 on 2025-02-14 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurse_users', '0036_nurselocation_nurse_users_locatio_9250ed_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nurseuseradditionalinfo',
            name='nurse_location',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nurse_user_additional_info', to='nurse_users.nurselocation'),
        ),
    ]
