# Generated by Django 5.0 on 2025-02-14 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nurse_users', '0037_alter_nurseuseradditionalinfo_nurse_location'),
    ]

    operations = [
    ]
