# Generated by Django 5.0 on 2025-02-15 06:50

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nurse_users', '0038_auto_20250214_1837'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='nurselocation',
            name='nurse_users_locatio_9250ed_idx',
        ),
        migrations.AddIndex(
            model_name='nurselocation',
            index=django.contrib.postgres.indexes.GistIndex(fields=['location'], name='nurse_users_locatio_43bd88_gist'),
        ),
    ]
