# Generated by Django 5.0 on 2025-02-15 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurse_users', '0039_remove_nurselocation_nurse_users_locatio_9250ed_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='nurseskills',
            index=models.Index(fields=['nurse', 'skill'], name='nurse_users_nurse_i_e3ab36_idx'),
        ),
        migrations.AddIndex(
            model_name='nurseuseradditionalinfo',
            index=models.Index(fields=['nurse_location'], name='nurse_users_nurse_l_6c0d4a_idx'),
        ),
    ]
