# Generated by Django 5.0 on 2025-02-15 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurse_users', '0040_nurseskills_nurse_users_nurse_i_e3ab36_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['status', 'end_date'], name='nurse_users_status_5609eb_idx'),
        ),
    ]
