# Generated by Django 5.0 on 2025-02-17 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurse_users', '0041_subscription_nurse_users_status_5609eb_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='nurseuser',
            name='display_user_name',
            field=models.CharField(default='one', max_length=123),
            preserve_default=False,
        ),
    ]
