# Generated by Django 5.0 on 2025-02-17 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurse_users', '0042_nurseuser_display_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nurseuser',
            name='display_user_name',
            field=models.CharField(max_length=123, unique=True),
        ),
    ]
