# Generated by Django 5.0 on 2025-02-18 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurse_users', '0043_alter_nurseuser_display_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='nurseuseradditionalinfo',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
