# Generated by Django 5.0 on 2025-02-21 05:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurse_users', '0044_nurseuseradditionalinfo_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='skill_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
