# Generated by Django 5.0 on 2025-02-21 08:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurse_users', '0046_alter_skills_skill_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='skill_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
