# Generated by Django 5.0 on 2025-02-21 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurse_users', '0047_alter_skills_skill_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nurseskills',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nurse_skill', to='nurse_users.skills'),
        ),
    ]
