# Generated by Django 5.0 on 2025-02-21 08:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurse_users', '0048_alter_nurseskills_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='skill_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
