# Generated by Django 5.0 on 2025-02-21 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurse_users', '0049_alter_skills_skill_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=124)),
                ('standard_price', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_skill', to='nurse_users.skills')),
            ],
            options={
                'verbose_name': 'زیر مهارت ها',
                'verbose_name_plural': 'زیر مهارت ها',
            },
        ),
    ]
