# Generated by Django 5.0 on 2025-02-21 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nurse_users', '0050_subskill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skills',
            name='price',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='price_description',
        ),
    ]
