# Generated by Django 5.0 on 2025-02-21 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurse_users', '0051_remove_skills_price_remove_skills_price_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='subskill',
            name='price_description',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
    ]
