# Generated by Django 5.0 on 2025-02-21 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurse_users', '0052_subskill_price_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='NurseSubSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_price', models.PositiveIntegerField(blank=True, null=True)),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nurse_subskill', to='nurse_users.nurseuseradditionalinfo')),
                ('subskill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nurse_subskill', to='nurse_users.subskill')),
            ],
            options={
                'verbose_name': 'زیر مهارت های انتخاب شده پرستار',
                'verbose_name_plural': 'زیر مهارت های انتخاب شده پرستار',
                'indexes': [models.Index(fields=['nurse', 'subskill'], name='nurse_users_nurse_i_4f4466_idx')],
                'unique_together': {('nurse', 'subskill')},
            },
        ),
    ]
