# Generated by Django 5.0 on 2025-02-22 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurse_users', '0053_nursesubskill'),
    ]

    operations = [
        migrations.AddField(
            model_name='nursesubskill',
            name='nurse_skill',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='nurse_dbuskill', to='nurse_users.nurseskills'),
            preserve_default=False,
        ),
    ]
