# Generated by Django 5.0 on 2025-02-22 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurse_users', '0054_nursesubskill_nurse_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nursesubskill',
            name='nurse_skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nurse_subskill', to='nurse_users.nurseskills'),
        ),
    ]
