# Generated by Django 5.0 on 2025-02-22 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nurse_users', '0055_alter_nursesubskill_nurse_skill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nurseskills',
            name='custom_price',
        ),
    ]
