# Generated by Django 5.0 on 2025-02-22 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurse_users', '0056_remove_nurseskills_custom_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='skill_description',
            field=models.TextField(max_length=300),
        ),
    ]
