# Generated by Django 5.0 on 2025-02-22 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurse_users', '0057_alter_skills_skill_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='title',
            field=models.CharField(help_text='فیلد اسلاگ - در انتخاب آن دقت کنید', max_length=124, unique=True),
        ),
    ]
