# Generated by Django 5.0 on 2025-02-22 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurse_users', '0058_alter_skills_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='title',
            field=models.CharField(max_length=124),
        ),
    ]
