# Generated by Django 5.0 on 2025-02-22 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurse_users', '0059_alter_skills_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='slug',
            field=models.SlugField(default='test/'),
            preserve_default=False,
        ),
    ]
