# Generated by Django 5.0 on 2025-02-22 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurse_users', '0060_skills_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='slug',
            field=models.SlugField(allow_unicode=True, unique=True),
        ),
    ]
