# Generated by Django 5.0 on 2025-02-22 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nurse_users', '0061_alter_skills_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skills',
            options={'ordering': ('id',), 'verbose_name': 'مهارت', 'verbose_name_plural': 'مهارت ها'},
        ),
    ]
