# Generated by Django 5.0 on 2025-02-23 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurse_users', '0062_alter_skills_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nurseuser',
            name='custom_user_id',
            field=models.UUIDField(editable=False, unique=True),
        ),
    ]
