# Generated by Django 5.0 on 2025-02-23 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nurse_users', '0063_alter_nurseuser_custom_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skills',
            name='skill_id',
        ),
    ]
