# Generated by Django 5.0 on 2025-02-23 12:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurse_users', '0064_remove_skills_skill_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='subskill',
            name='subskill_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
