# Generated by Django 5.0 on 2025-02-23 12:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurse_users', '0065_subskill_subskill_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subskill',
            name='subskill_uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
