# Generated by Django 5.0 on 2025-02-24 08:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurse_users', '0067_alter_subskill_subskill_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='nursesubskill',
            name='nurse_subskill_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
