# Generated by Django 5.0 on 2025-02-24 08:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurse_users', '0068_nursesubskill_nurse_subskill_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nursesubskill',
            name='nurse_subskill_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
