# Generated by Django 5.0 on 2025-02-24 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurse_users', '0069_alter_nursesubskill_nurse_subskill_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
