# Generated by Django 5.0 on 2025-02-24 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurse_users', '0070_skills_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='subskill',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
