# Generated by Django 5.0 on 2025-03-03 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurse_users', '0071_subskill_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nurseuseradditionalinfo',
            name='description',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
