# Generated by Django 5.0 on 2025-03-08 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurse_users', '0072_alter_nurseuseradditionalinfo_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='nurseuseradditionalinfo',
            name='average_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nurseuseradditionalinfo',
            name='rating_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
