# Generated by Django 5.0 on 2025-03-11 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurse_users', '0073_nurseuseradditionalinfo_average_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationrequest',
            name='admin_message',
            field=models.CharField(blank=True, max_length=124, null=True),
        ),
    ]
