# Generated by Django 5.0 on 2025-03-14 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurse_users', '0074_registrationrequest_admin_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='nurseuseradditionalinfo',
            name='star',
            field=models.BooleanField(default=False),
        ),
    ]
