# Generated by Django 5.0 on 2025-03-21 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurse_users', '0075_nurseuseradditionalinfo_star'),
    ]

    operations = [
        migrations.AddField(
            model_name='nurseuser',
            name='identity_card_picture',
            field=models.ImageField(default='1', upload_to='storage/nurse/identity_card/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nurseuser',
            name='national_id_number_picture',
            field=models.CharField(default='1', max_length=50),
            preserve_default=False,
        ),
    ]
