# Generated by Django 5.0 on 2025-03-21 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nurse_users', '0076_nurseuser_identity_card_picture_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nurseuser',
            old_name='national_id_number_picture',
            new_name='national_id_number',
        ),
    ]
