# Generated by Django 5.0 on 2025-05-21 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurse_users', '0077_rename_national_id_number_picture_nurseuser_national_id_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField()),
                ('invoice_date', models.DateField(auto_now_add=True)),
                ('invoice_datetime', models.DateTimeField(auto_now_add=True)),
                ('invoice_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_payments', to='nurse_users.nurseuser')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_payments', to='nurse_users.subscriptionplan')),
            ],
            options={
                'verbose_name': 'خرید اشتراک',
                'verbose_name_plural': 'خرید اشتراک ها',
            },
        ),
    ]
