# Generated by Django 5.0 on 2025-05-21 12:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurse_users', '0078_subscriptionpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='product_uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
