# Generated by Django 5.0 on 2025-05-21 12:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurse_users', '0079_subscriptionplan_product_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='product_uid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
