# Generated by Django 5.0 on 2025-05-26 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurse_users', '0080_alter_subscriptionplan_product_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionpayment',
            name='is_payed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionpayment',
            name='is_vertify',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionpayment',
            name='transaction_refrence_id',
            field=models.CharField(blank=True, max_length=124, null=True),
        ),
    ]
