# Generated by Django 5.0 on 2025-05-29 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nurse_users', '0081_subscriptionpayment_is_payed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptionpayment',
            old_name='is_payed',
            new_name='is_paid',
        ),
        migrations.RenameField(
            model_name='subscriptionpayment',
            old_name='is_vertify',
            new_name='is_verified',
        ),
        migrations.RenameField(
            model_name='subscriptionpayment',
            old_name='transaction_refrence_id',
            new_name='transaction_reference_id',
        ),
    ]
