# Generated by Django 5.0 on 2025-05-29 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurse_users', '0082_rename_is_payed_subscriptionpayment_is_paid_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptionpayment',
            options={'ordering': ['-created_at'], 'verbose_name': 'خرید اشتراک', 'verbose_name_plural': 'خرید اشتراک ها'},
        ),
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='is_paid',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
