# Generated by Django 5.0 on 2025-06-03 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurse_users', '0083_alter_subscriptionpayment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nurseuser',
            name='identity_card_picture',
            field=models.ImageField(upload_to='storage/nurse/identity_card/<function get_unique_filename2 at 0x7f89e550c280>'),
        ),
        migrations.AlterField(
            model_name='nurseuser',
            name='ministry_proof_picture',
            field=models.ImageField(upload_to='storage/nurse/ministry_proof/<function get_unique_filename2 at 0x7f89e550c280>'),
        ),
        migrations.AlterField(
            model_name='nurseuser',
            name='profile_picture',
            field=models.ImageField(upload_to='storage/nurse/profile/<function get_unique_filename2 at 0x7f89e550c280>'),
        ),
    ]
