# Generated by Django 5.0 on 2025-06-03 11:47

import nurse_users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurse_users', '0084_alter_nurseuser_identity_card_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nurseuser',
            name='identity_card_picture',
            field=models.ImageField(upload_to=nurse_users.models.identity_card_picture_path),
        ),
        migrations.AlterField(
            model_name='nurseuser',
            name='ministry_proof_picture',
            field=models.ImageField(upload_to=nurse_users.models.ministry_proof_picture_path),
        ),
        migrations.AlterField(
            model_name='nurseuser',
            name='profile_picture',
            field=models.ImageField(upload_to=nurse_users.models.nurse_profile_picture_path),
        ),
    ]
