# Generated by Django 5.0 on 2025-09-16 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurse_users', '0085_alter_nurseuser_identity_card_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nurseuser',
            name='is_legal_entity',
            field=models.BooleanField(default=False),
        ),
    ]
